<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<title>PT. Roseg Indo Properties</title>
	<link rel="stylesheet" href="asset/css/style.css" type="text/css" media="all" />
    <link rel="stylesheet" href="asset/css/formstyle.css" type="text/css" media="all" />
	<script src="asset/js/jquery-1.4.1.min.js" type="text/javascript"></script>
	<script src="asset/js/jquery.jcarousel.pack.js" type="text/javascript"></script>
	<script src="asset/js/jquery-func.js" type="text/javascript"></script>
</head>
<body>
<div id="page" class="shell">
	<!-- Logo + Search + Navigation -->
	<div id="top">
		<div class="cl">&nbsp;</div>
		<h1 id="logo"><a href="#">Insist</a></h1>
		<form action="" method="post" id="search">
			<div class="field-holder">
				<input type="text" class="field" value="Search" title="Search" />
			</div>
			<input type="submit" class="button" value="Search" />
			<div class="cl">&nbsp;</div>
		</form>
		<div class="cl">&nbsp;</div>
		<div id="navigation">
			<ul>
			    <li>
			    	<a href="index.php" class="active"><span>home</span></a>
			    </li>
			    <li>
			    	<a href="article.php?pil=product"><span>Project</span></a>
			    </li>
			    <li>
			    	<a href="article.php?pil=struktur"><span>Partners</span></a>
			    </li>
                 <li>
			    	<a href="article.php?pil=struktur"><span>organization structure</span></a>
			    </li>
			    <li>
			    	<a href="article.php?pil=contact_us"><span>Contact Us</span></a>
			    </li>
               
                
			</ul>
		</div>	
	</div>
	<!-- END Logo + Search + Navigation -->
	<!-- Header -->
	<div id="header">
		<!-- Slider -->
		
		<div id="slider">
			<div id="slider-holder">
				<ul>
                	<li>
				    	<div class="slide-si">
				    		<h2 class="si"></h2>
				    </li>
				    <li>
				    	<div class="slide-info">
				    		<h2 class="uc"></h2>
				    		<p>Unified communications (UC) is the integration of real-time communication services such as instant messaging (chat), presence information, telephony (including IP telephony), video conferencing,</p>
				    		<a href="article.php?pil=uc" class="button-more">More</a>
				    	</div>
				    	<div class="slide-image">
				    		<img src="#" alt="slide1" />
				    	</div>
				    </li>
				    <li>
				    	<div class="slide-info">
				    		<h2 class="utm"></h2>
				    		<p>Network Infrastructure is an interconnected group of computer systems linked by the various parts of a telecommunicationsarchitecture.</p>
				    		<a href="articel.php?pil=utm" class="button-more">More</a>
				    	</div>
				    	<div class="slide-image">
				    		<img src="#" alt="slide2" />
				    	</div>
				    </li>
				    <li>
				    	<div class="slide-info">
				    		<h2 class="it_security"></h2>
				    		<p>Security Intelligence is the real-time collection, normalization, and analysis of the data generated by users, applications and infrastructure that impacts the IT security and risk posture of an enterprise.</p>
				    		<a href="articel.php?pil=it_security" class="button-more">More</a>
				    	</div>
				    	<div class="slide-image">
				    		<img src="#" alt="slide3" />
				    	</div>
				    </li>
				</ul>
			</div>
			<div class="slider-nav">
				<a href="#" class="prev">Previous</a>
				<a href="#" class="next">Next</a>
			</div>
		</div>
	
		<!-- END Slider -->	
	</div>
	<!-- END Header -->
	<!-- Main -->
	<div id="main">
        <!-- Two Column Content -->
		<div class="cols two-cols">
			<div class="cl">&nbsp;</div>
		  <div class="col" style="width:300px; box-shadow: 0px 3px 7px -3px rgba(1, 1, 1, 1);">
				<form name="form1" method="post" action="login_proses.php">
				  <h1 style="background-image:url(asset/css/images/login.gif);
                   height:15px;  margin-bottom:20px; 
                   padding:12px; 
                   color:#FFF; text-align:center;"> Login </h1>
                  <table width="100" border="0">
				    <tr>
				      <td><label for="username"></label>
			          <input name="username" type="text" id="username" class="inputStylelog" size="35" placeholder="Username/Email"></td>
			        </tr>
				    <tr>
				      <td><label for="password"></label>
			          <input name="password" type="password" id="password" class="inputStylelog" size="35" placeholder="Password"></td>
			        </tr>
				    <tr>
				      <td><input type="submit" name="signin" id="signin" class="btnStyle" value="Sign in">
			          </td>
			        </tr>
			      </table>
		      </form>
			</div>
			<div class="col col-last" style="width:630px;">
				<?php 
			  	 if(isset($_GET['pil'])){
				    	$pil=$_GET['pil'];
					}else{
						$pil="";	
				    		}
				 if($pil=="contact_us"){
				   	include("contact_us.html");
				  }
				 if($pil=="it_security") {
					 include("it_security.html");
					 }
				 if($pil=="utm") {
					 include("utm.html");
					 } 
				 if($pil=="uc") {
					 include("uc.html");
					 } 	
				 if($pil=="product") {
					 include("product.html");
					 }  
				 if($pil=="struktur") {
					 include("struktur_organisasi.html");
					 }  	 
				?>
				
			</div>
			<div class="cl">&nbsp;</div>
		</div>
		<!-- END Two Column Content -->
        
	</div>
	<!-- END Main -->
	<!-- Footer -->
	<div id="footer">
		<p class="right">&copy; 2015-PT.Roseg Indo Properties&nbsp; Design by <a href="http://facebook.com/thefaqih" target="_blank">Muhammad Fakih</a></p>
		<p><a href="index.php">Home</a><span>&nbsp;</span><a href="#">Project</a><span>&nbsp;</span><a href="#">Partners</a><span>&nbsp;</span><a href="#">Contact Us</a></p>
		<div class="cl">&nbsp;</div>
	</div>
	<!-- END Footer -->
	<br />
</div>
</body>
</html>