<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<title>PT. Roseg Indo Properties</title>
	<link rel="stylesheet" href="asset/css/style.css" type="text/css" media="all" />
    <link rel="stylesheet" href="asset/css/formstyle.css" type="text/css" media="all" />
	<script src="asset/js/jquery-1.4.1.min.js" type="text/javascript"></script>
	<script src="asset/js/jquery.jcarousel.pack.js" type="text/javascript"></script>
	<script src="asset/js/jquery-func.js" type="text/javascript"></script>
	<script src="asset/js/num.js" type="text/javascript"></script>
</head>
<body>
<div id="page" class="shell">
	<!-- Logo + Search + Navigation -->
	<div id="top">
	  <div class="cl">&nbsp;</div>
		<h1 id="logo"><a href="#">Roseg Indo</a></h1>
		<form action="" method="post" id="search">
			<div class="field-holder">
				<input type="text" class="field" value="Search" title="Search" />
			</div>
			<input type="submit" class="button" value="Search" />
            
			<div class="cl">&nbsp;</div>
		</form>
		<div class="cl">&nbsp;</div>
		<div id="navigation">
			<ul>
			    <li>
			    	<a href="index.php" class="active"><span>home</span></a>
			    </li>
			    <li>
			    	<a href="article.php?pil=product"><span>Projects</span></a>
			    </li>
			    <li>
			    	<a href="article.php?pil=contact_us"><span>Partners</span></a>
			    </li>
                <li>
			    	<a href="article.php?pil=struktur"><span>organization structure</span></a>
			    </li>
			    <li>
			    	<a href="article.php?pil=contact_us"><span>Contact Us</span></a>
			    </li>
                
			</ul>
		</div>	
	</div>
    
	<!-- END Logo + Search + Navigation -->
	<!-- Header -->
	<div id="header">
		<!-- Slider -->
		<div id="slider">
			<div id="slider-holder">
				<ul>
                	<li>
				    	<div class="slide-si">
				    		<h2 class="si"></h2>
				    </li>
				    <li>
				    	<div class="slide-info">
				    		<h2 class="uc"></h2>
				    		<p>Unified communications (UC) is the integration of real-time communication services such as instant messaging (chat), presence information, telephony (including IP telephony), video conferencing,</p>
				    		<a href="article.php?pil=uc" class="button-more">More</a>
				    	</div>
				    	<div class="slide-image">
				    		<img src="asset/css/images/avaya.png" alt="" />
				    	</div>
				    </li>
				    <li>
				    	<div class="slide-info">
				    		<h2 class="utm"></h2>
				    		<p>Network Infrastructure is an interconnected group of computer systems linked by the various parts of a telecommunicationsarchitecture.</p>
				    		<a href="articel.php?pil=utm" class="button-more">More</a>
				    	</div>
				    	<div class="slide-image">
				    		<img src="asset/css/images/fortinet.png" alt="" />
				    	</div>
				    </li>
				    <li>
				    	<div class="slide-info">
				    		<h2 class="it_security"></h2>
				    		<p>Security Intelligence is the real-time collection, normalization, and analysis of the data generated by users, applications and infrastructure that impacts the IT security and risk posture of an enterprise.</p>
				    		<a href="articel.php?pil=it_security" class="button-more">More</a>
				    	</div>
				    	<div class="slide-image">
				    		<img src="asset/css/images/ibm.png" alt="" />
				    	</div>
				    </li>
				</ul>
			</div>
			<div class="slider-nav">
				<a href="#" class="prev">Previous</a>
				<a href="#" class="next">Next</a>
			</div>
		</div>
		<!-- END Slider -->	
	</div>
	<!-- END Header -->
	<!-- Main -->
	<div id="main">
        <!-- Two Column Content -->
		<div class="cols two-cols">
			<div class="cl">&nbsp;</div>
		  <div class="col" style="width:300px; box-shadow: 0px 3px 7px -3px rgba(1, 1, 1, 1);">
				<form name="form1" method="post" action="login_proses.php">
                  <table width="100" border="0">
				    <tr><h1 style="background-image:url(asset/css/images/login.gif);
                   height:15px;  margin-bottom:20px; 
                   padding:12px; 
                   color:#FFF; text-align:center;"> Login </h1>
                  <table width="100" border="0">
				    <tr>
				      <td><label for="username"></label>
			          <input name="username" type="text" id="username" class="inputStylelog" size="35" placeholder="Username/Email"></td>
			        </tr>
				    <tr>
				      <td><label for="password"></label>
			          <input name="password" type="password" id="password" class="inputStylelog" size="35" placeholder="Password"></td>
			        </tr>
				    <tr>
				      <td><input type="submit" name="signin" id="signin" class="btnStyle" value="Sign in">
			          </td>
			        </tr>
			      </table>
		      </form>
				<form action="proses_absensi.php" method="post">
					<input type="hidden" name="tgl" value="<?=date('Y-m-d');?>" required>
					<input type="hidden" name="jam" value="<?=date("H:i:s");?>" required>
					<table width="100" border="0">
						<tr><h1 style="background-image:url(asset/css/images/login.gif);
						height:15px;  margin-bottom:20px; 
						padding:12px; 
						color:#FFF; text-align:center;"> Absensi </h1>
						<table width="100" border="0">
						<tr>
							<td><label for="username"></label>
							<input name="idnya" type="text" id="username" class="inputStylelog" size="35" placeholder="ID Anda" onKeyPress="return isNumber(event)" maxlength="15"></td>
						</tr>
						<tr>
							<td><input type="submit" name="absen" id="signin" class="btnStyle" value="<?=(date('H')>="00" and date('H')<="16")? "Datang" : "Pulang";?>">
						</td>
						</tr>
					</table>
				</form>
		</div>
			<div class="col col-last" style="width:630px;">
				<h2><strong>Selamat Datang di PT. Roseg Indo properties</strong></h2></br>
				<p>Roseg Indo Property mulai berdiri pada tahun 2008 kami mencoba memulai usaha kami dalam bidang jasa property serta periklanan. Yang pertama kami lakukan adalah khusnudon (berprasangka baik/ positive thingking) karena ini merupakan Salah satu kunci sukses yaitu apa yang ada dalam fikiran. Bahwa yang kami lakukan akan mendapat ridho-Nya dan tentunya mendapat tanggapan positif dari masyarakat.</p>

<p>Pekerjaan yang kami lakukan ini tak ubahnya sebagai broker namun lebih professional karena ada payung hukumnya. Alasan kami mendirikan usaha ini adalah untuk mencapai taraf hidup yang lebih baik (freedom financial) yang merupakan impian hampir semua orang.</p>
                <h2><strong>Our Vision</strong></h2>
				<p>Menjadi Perusahaan Terbaik dan Terdepan Dalam Pengembangan Perumahan dan Menjadikan Roserg Indo sebagai portal pencarian dan jual beli properti serta menciptakan forum iklan dengan slogan “IKLAN SAMPAI LAKU (IKLAN SAK PAYUNE)”. Sehingga diharapkan menjadi wadah komunikasi, tempat berkumpulnya para penjual dan pembeli property maupun pemilik usaha atau jasa yang lain. Memasarkan secara professional dan sekaligus tempat berkarir bagi semua orang yang ingin meraih sumber pendapatan melalui internet.</p>

				<h2><strong>Our Mision</strong></h2>
				<p>Semangat kami adalah semangat anda semua untuk berkembang dan maju bersama. Dengan usaha dan konsep pemasaran kami yang tiada henti maka anda tidak akan pernah merasa rugi bergabung bersama kami.</p>
                <p>Menciptakan karya arsitektur yang bernilai tinggi dengan memperhatikan aspek-aspek kualitas, keindahan, kenyamanan, tren arsitektur, lingkungan dan alam,</p>
				
                
			</div>
			<div class="cl">&nbsp;</div>
		</div>
		<!-- END Two Column Content -->
        
	</div>
	<!-- END Main -->
	<!-- Footer -->
	<div id="footer">
		<p class="right">&copy; 2015 -PT. Roseg Indo properties -&nbsp; Design by <a href="http://facebook.com/thefaqih" target="_blank">Muhammad Fakih</a></p>
		<p><a href="index.php">Home</a><span>&nbsp;</span><a href="#">Projects</a><span>&nbsp;</span><a href="#">Partners</a><span>&nbsp;</span><a href="#">Contact Us</a></p>
		<div class="cl">&nbsp;</div>
	</div>
	<!-- END Footer -->
	<br />
</div>
</body>
</html>